### ISSUE TITLE
Doubling of echoed characters in ConsoleReader from Windows client when using Socket I/O Stream.

### ISSUE THREAD

**Issue by bensteele** [jline/jline2#120]
Creating a ConsoleReader with a Socket for I/O streams:
ConsoleReader reader = new ConsoleReader(Socket.getInputStream(),
        Socket.getOutputStream());

results in output like:
prompt> tteessttiinngg

When typing the word "testing".

** Tested on windows 7 with JRE 1.6 and 1.7

A reference implementation class using this can be found at:
https://github.com/bensteele/jirrigate/blob/master/src/main/java/org/bensteele/jirrigate/TelnetServer.java#L40

On the other hand in a linux based client test I don't get the doubling up of echoed chars, but auto-complete is broken.

Is this the right way to deal with a Socket based console with jline?

**Comment by gnodet** [comment]
If you use a virtual terminal, you need to implement your own terminal.
In your case, I think the terminal is echoing, but jline does not know it because it points to the console instead of the real telnet client terminal.

At least, in the terminal you give to the console reader, it has to say that the echo is active, in which case it will delete the character echoed, so you should not have all the characters duplicated.

**Comment by gnodet** [comment]
Related to #195

**Comment by gnodet** [comment]
I think we could provide a `VirtualTerminal` implementation in jline.
For virtual terminals, one should definitely not use the `UnixTerminal` or `WindowsTerminal` which should be used on the client side.

By default, the client side on windows has echo enabled.  The `WindowsTerminal` disables that.  On the server side, you need to know if the client is echoing or not and that should be reflected in your virtual terminal `Terminal.isEchoEnabled` method.
